# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loom_version=1.17-SNAPSHOT
loader_version=0.19.3

# Mod Properties
version=1.0.0
group=com.gabrielaraujo9001
archives_base_name=cropspread

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.160.0+26.2
fabric_version=0.160.0+26.2
